# 06.09.23

# PLOTTING WITH REAL-TIME DATA

## Deeper insights can be gained from the data by visualizing it using Matplotlib.
## Matplotlib has several kinds of plots. These plots can be used to get a visual understanding of various features present in the data, analyze them better, and present the data to the stakeholders.

## Visualizing the data using Matplotlib

In [ ]:
# imprting the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# importing the data
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/PYTHON FOR DS/0.FILES TO BE USED/auto_mpg.csv')

# getting column names, missing values and their dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

### The 'horsepower' column has some null values which needs to be replaced.

In [ ]:
# replacing the null value in 'horsepower' with its mean value
df['horsepower'].fillna(df['horsepower'].mean(), inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

### This transformed data is used to visualize using differnet kinds of plots available in Matplotlib library.